### ISSUE TITLE
[Documentation] requirements.txt wanted

### ISSUE THREAD

**Issue by ann-lab52** [unicamp-dl/retailGPT#1]
Hi @Brunoatf, congratulation on you and your team for publishing RetailGPT. 

It's seem like RetailGPT is missing `requirements.txt`, can you update this to the repo? This will help other developers easier to  participate in RetailGPT.

Thank you very much.

**Comment by Brunoatf** [comment]
Hi Ann! Thank you for your kind feedback. I used Poetry for managing the dependencies in each application of the system, but I will be adding a requirements.txt for convenience later this week.

I will also fix some problems related to running everything in Docker, so that the application becomes easier to run.

**Comment by ann-lab52** [comment]
So happy to hear this good news from you, I'm looking forward to your next update. I will close this issue then. 

Have a nice day!
